### ISSUE TITLE
Pandas Tutorial

### ISSUE THREAD

**Issue by TomAugspurger** [dask/scipy-tutorials-2018#6]
For data, we can use the public ones on Anaconda's gcs (NY taxi dataset). These are used in the pangeo examples I believe.

cc @deniederhut @jorisvandenbossche

**Comment by TomAugspurger** [comment]
@martindurant @mrocklin, are we still planning to provide cluster resources to other tutorials? What will that process look like (setting up compute vs. the tutorial authors providing materials)? I can of course take care of it all if necessary.

@deniederhut @jorisvandenbossche for content, I was thinking something like https://github.com/TomAugspurger/dask-tutorial-pycon-2018/blob/master/05-distributed-dataframes-and-efficiency.ipynb

We'll spend maybe 5-10 minutes getting people on their cluster.

We'll take ~5 minutes to introduce the basics of dask dataframe (like a pandas dataframe but partitioned along the index) and the distributed dashboard.

And then it'll be mostly exercises retreading stuff they've already seen, but on a cluster. This may be a good topic to end on.

**Comment by deniederhut** [comment]
> This may be a good topic to end on.

I concur. Thanks for taking the lead on this!

**Comment by TomAugspurger** [comment]
I'm doing a test deploy under the cluster name `pandas-scipy` now. It's in the same GCP project as the dask one, but I *think* there won't be any clashes. Regardless, I'll remove this `pandas-scipy` deployment until Tuesday morning.

**Comment by TomAugspurger** [comment]
We were able to demo dask and students had a bit of time to play with their cluster.
