### ISSUE TITLE
Archived?

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/scipy-tutorials-2018#8]
Should this repo now be archived or are there plans for future re-use?

**Comment by martindurant** [comment]
It should be reasonable to suppose that https://github.com/dask/dask-tutorial supersedes this; but since I don't think there is a more recent tutorial recording out there, it may be worth keeping around the exact material that goes with it for a while.

**Comment by jacobtomlinson** [comment]
Sure. Archiving makes it read only and displays a banner right? To show it is not under active development but still makes it available.

Like this https://github.com/dask/knit.

**Comment by martindurant** [comment]
So long as it can still be found, that sounds fine

**Comment by jsignell** [comment]
I think the time has come! @jrbourbeau can you please archive this :)

**Comment by martindurant** [comment]
I'll do it
